version: '3'

networks:
  indrz-net:

services:
  db_indrz:
    hostname: db_indrz
    container_name: db_indrz
    image: kartoza/postgis:13.0
    volumes:
      - ${PWD}/data/geo-db-data:/var/lib/postgresql
    ports:
      - ${POSTGRES_EXT_PORT}:5432
    networks:
      - indrz-net
    env_file:
      - devops/docker-env/db.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  geoserver:
    hostname: geoserver
    container_name: geoserver
    image: indrz/geoserver:2.18.0
    build:
      context: .
      dockerfile: devops/docker/geoserver/Dockerfile
    volumes:
      - ${PWD}/data/geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    restart: on-failure
    env_file:
      - devops/docker-env/geoserver.env
    depends_on:
      - db_indrz
    networks:
      - indrz-net
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db-backups:
    hostname: db-backups
    container_name: db-backups
    image: kartoza/pg-backup:13.0
    volumes:
      - ${PWD}/data/db-backups:/opt/data/backups
    env_file:
      - devops/docker-env/db-backups.env
    restart: always
    depends_on:
      - db_indrz

# INDRZ Backend
  indrz_be:
    container_name: indrz_be
    hostname: indrz_be
    image: indrz/indrz-be:latest
    build:
      context: .
      dockerfile: devops/docker/indrz/Dockerfile
    ports:
      - 8000:8000
    networks:
      - indrz-net
    depends_on:
      - db_indrz
    volumes:
      - ${PWD}/indrz:/usr/src/app
      - ${PWD}/data/indrz/media:/opt/data/media
      - ${PWD}/data/indrz/static:/opt/data/static
      - ${PWD}/data/indrz/logs:/usr/src/app/logs
    restart: always
    env_file:
      - devops/docker-env/indrz.env

# NGINX
  nginx:
    container_name: nginx
    hostname: nginx
    image: indrz/nginx:latest
    build:
      context: .
      dockerfile: devops/docker/nginx/Dockerfile
    volumes:
      - ${PWD}/data/indrz/static:/opt/data/static
      - ${SSL_CERTIFICATES_PATH}:/etc/ssl
      - ${PWD}/data/nginx/www:${WEB_FOLDER}
    ports:
      - 80:80
      - 443:443
    networks:
      - indrz-net
    restart: always
    depends_on:
      - indrz_be
