---
- hosts: yourlivehost
  remote_user: root
  become: yes
  become_user: wsgi
  gather_facts: no
  vars:
    # Application settings.
    #django_python_interpreter: /usr/bin/python3
    repo_dir: "/srv/indrz_src/"
    static_dir: "/srv/www/example.com/wsgi/static"
    django_src_dir: "/srv/indrz_src/indrz"
    django_deploy_dir: "/srv/www/example.com/wsgi"
    django_conf_dir: "/srv/indrz_conf"
    requirements_file: "{{ django_src_dir }}/requirements/requirements.txt"
    gitlabuser: "someusername"
    gitlabpwd: "somepwd"

  tasks:
  - name: pull branch master
    git:
      repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpwd }}@gitlab.com/indrz/indrz-backend.git"
      dest: "{{ repo_dir }}"

  - name: delete deploy dir
    command: rm -rf "{{ django_deploy_dir }}"/indrz
    args:
      chdir: "{{ django_deploy_dir }}"

  - name: copy to deploy dir
    command: cp -R "{{ django_src_dir }}" "{{ django_deploy_dir }}/indrz"

  - name: copy secret settings
    command: cp secret_settings.py "{{ django_deploy_dir }}/indrz/settings/"
    args:
      chdir: "{{ django_conf_dir }}"

  - name: install pip requriements
    pip:
      requirements: "{{ requirements_file }}"
      executable: pip3
      extra_args: --user
    become: true
    become_user: wsgi

  - name: Reload Apache httpd
    command: service httpd reload
    become: true
    become_user: root

