---
- hosts: yourHostAnsible
  remote_user: root
#  become: yes
#  become_user: wsgi
  gather_facts: no
  vars:
    # Application settings.
    #django_python_interpreter: /usr/bin/python3
    repo_dir: "/srv/indrz_src/"
    static_dir: "/srv/www/html/static"
    django_dir: "/srv/indrz_src/indrz"
    requirements_file: "{{ django_dir }}/requirements/requirements.txt"
    gitlabuser: ""
    gitlabpwd: ""

  tasks:
    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - sysstat
        - htop
        - git
        - vim
        - gdal-bin

